version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: microservicesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=microservicesdb
      - DB_USER=postgres
      - DB_PASSWORD=password
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_PORT=9411
    depends_on:
      - postgres
      - zipkin

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=microservicesdb
      - DB_USER=postgres
      - DB_PASSWORD=password
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_PORT=9411
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=8081
      - NOTIFICATION_SERVICE_HOST=notification-service
      - NOTIFICATION_SERVICE_PORT=8083
    depends_on:
      - postgres
      - zipkin
      - user-service

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    environment:
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_PORT=9411
    depends_on:
      - zipkin

volumes:
  postgres-data: 