apiVersion: v1
kind: Secret
metadata:
  name: otel-credentials
  namespace: last9-otel-demo
type: Opaque
data:
  otlp-endpoint: "aHR0cHM6Ly9vdGxwLWFwczEubGFzdDkuaW86NDQz"
  otlp-auth: ${OTLP_AUTH_BASE64}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: last9-otel-demo
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp-aps1.last9.io:443"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_LOGS_EXPORTER: "none"
  OTEL_METRICS_EXPORT_INTERVAL: "10000"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_PROPAGATORS: "b3"
  OTEL_SDK_DISABLED: "false"
  OTEL_TRACES_EXPORT_INTERVAL: "10000"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
  OTEL_EXPORTER_OTLP_HEADERS: "Authorization=${OTLP_AUTH}" 