apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: last9-otel-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
      - name: notification-service
        image: docker.io/last9mukta/notification-service:otel
        ports:
        - containerPort: 8083
        env:
        - name: OTEL_SERVICE_NAME
          value: "notification-service"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            secretKeyRef:
              name: otel-secret
              key: otel-headers
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=notification-service,service.namespace=last9-otel-demo,deployment.environment=production"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/notificationdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        envFrom:
        - configMapRef:
            name: otel-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: last9-otel-demo
spec:
  selector:
    app: notification-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP 