apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: last9-otel-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: last9mukta/notification-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: ZIPKIN_HOST
          value: "zipkin-service"
        - name: ZIPKIN_PORT
          value: "9411"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: last9-otel-demo
spec:
  selector:
    app: notification-service
  ports:
  - port: 8083
    targetPort: 8083 