apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: last9-otel-demo
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp-aps1.last9.io:443"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "none"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"