apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: last9-otel-demo
data:
  POSTGRES_DB: microservicesdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: last9-otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: last9-otel-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: last9-otel-demo
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432 