apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: microservices-demo
type: Opaque
data:
  # echo -n "your-password" | base64
  postgres-password: BASE64_ENCODED_PASSWORD
  db-password: BASE64_ENCODED_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: microservices-demo
type: kubernetes.io/dockerconfigjson
data:
  # echo -n "your-registry-username:your-registry-password" | base64
  .dockerconfigjson: BASE64_ENCODED_DOCKER_CONFIG
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: microservices-demo
type: Opaque
data:
  # echo -n "your-aws-access-key" | base64
  aws-access-key-id: BASE64_ENCODED_AWS_ACCESS_KEY
  # echo -n "your-aws-secret-key" | base64
  aws-secret-access-key: BASE64_ENCODED_AWS_SECRET_KEY 