apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: last9mukta/user-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "microservicesdb"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        - name: ZIPKIN_HOST
          value: "zipkin-service"
        - name: ZIPKIN_PORT
          value: "9411"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservices-demo
spec:
  selector:
    app: user-service
  ports:
  - port: 8081
    targetPort: 8081 