server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:userdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sleuth:
    zipkin:
      base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}
    sampler:
      probability: 1.0

weather:
  api:
    url: ${WEATHER_API_URL:https://api.open-meteo.com/v1/forecast}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.demo.userservice: DEBUG
    org.springframework.cloud.sleuth: DEBUG 