server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orderdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sleuth:
    zipkin:
      base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}
    sampler:
      probability: 1.0

user:
  service:
    url: http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8081}

notification:
  service:
    url: http://${NOTIFICATION_SERVICE_HOST:localhost}:${NOTIFICATION_SERVICE_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.demo.orderservice: DEBUG
    org.springframework.cloud.sleuth: DEBUG 