apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-ui
  namespace: last9-otel-demo
  labels:
    app: microservices-ui
    region: ap-south-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-ui
      region: ap-south-1
  template:
    metadata:
      labels:
        app: microservices-ui
        region: ap-south-1
    spec:
      containers:
      - name: microservices-ui
        image: docker.io/last9mukta/microservices-ui:otel
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: BACKEND_URL
          value: "http://user-service.last9-otel-demo.svc.cluster.local:8081"
        - name: ORDER_SERVICE_URL
          value: "http://order-service.last9-otel-demo.svc.cluster.local:8082"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service.last9-otel-demo.svc.cluster.local:8083"
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-ui
  namespace: last9-otel-demo
  labels:
    app: microservices-ui
    region: ap-south-1
spec:
  selector:
    app: microservices-ui
    region: ap-south-1
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP 